# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Paper Properties
minecraft_version=1.20.1

# Plugin Properties
version=1.0.0
group=com.indogeek.deathroulette

# Kotlin
kotlin_version=1.9.24

# Dependencies
paper_api_version=1.20.1-R0.1-SNAPSHOT